import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, BookOpen, ChevronDown, CircleHelp, Gauge, Layers3, Play, Radio, RefreshCw, ShieldCheck, SlidersHorizontal, Terminal, Wifi } from 'lucide-react'

const fallbackReport = {
  project: 'Quant Market Microstructure Lab',
  status: 'research-only; no live trading',
  components: ['price-time-priority order book', 'binary deterministic replay', 'queue-aware execution simulator', 'top-of-book microstructure features', 'read-only Kalshi market adapter'],
  controls: { fees: 'integer ticks', latency: 'explicit availability timestamp', queue_position: 'modelled as contracts ahead', credentials: 'none required for public adapter' },
  interpretation: 'A signal is not considered executable until queue position, latency, fees, and partial fills are included.'
}

const markets = [
  { ticker: 'KXBTC-26SEP18-T115000', title: 'Bitcoin above $115,000', venue: 'Kalshi', yes: 0.55, no: 0.45, spread: 0.03, volume: '18.4K', reward: '$428' },
  { ticker: 'KXFED-26SEP-F4.00', title: 'Fed funds target range', venue: 'Kalshi', yes: 0.63, no: 0.37, spread: 0.02, volume: '9.7K', reward: '$291' },
  { ticker: 'KXNBA-26SEP18-LAL', title: 'Lakers win tonight', venue: 'Kalshi', yes: 0.57, no: 0.43, spread: 0.05, volume: '4.2K', reward: '$84' }
]

const asks = [{ px: '0.58', qty: 820 }, { px: '0.57', qty: 430 }, { px: '0.56', qty: 190 }]
const bids = [{ px: '0.54', qty: 260 }, { px: '0.53', qty: 610 }, { px: '0.52', qty: 980 }]

function formatNumber(value) { return new Intl.NumberFormat('en-US').format(value) }
function Metric({ label, value, detail, tone = '' }) { return <div className="metric"><span>{label}</span><strong className={tone}>{value}</strong>{detail && <small>{detail}</small>}</div> }
function SectionHeader({ icon: Icon, eyebrow, title, action }) { return <div className="section-head"><div><div className="eyebrow"><Icon size={14} /> {eyebrow}</div><h2>{title}</h2></div>{action}</div> }
function Sparkline({ points, positive = true }) { const max = Math.max(...points), min = Math.min(...points); const path = points.map((p, i) => `${(i / (points.length - 1)) * 100},${100 - ((p - min) / (max - min || 1)) * 80 - 10}`).join(' '); return <svg className="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={path} fill="none" stroke={positive ? '#64e6ab' : '#fb7185'} strokeWidth="2.4" vectorEffect="non-scaling-stroke" /></svg> }
function OrderBook() { return <div className="book"><div className="book-head"><span>PRICE</span><span>SIZE</span><span>DEPTH</span></div><div className="book-side asks">{asks.map((x) => <div className="book-row" key={x.px}><i style={{ width: `${x.qty / 10}%` }} /><b>{x.px}</b><span>{x.qty}</span><em>{(x.qty / 10).toFixed(0)}%</em></div>)}</div><div className="midline"><span>mid 0.55</span><span>spread 3¢</span></div><div className="book-side bids">{bids.map((x) => <div className="book-row" key={x.px}><i style={{ width: `${x.qty / 10}%` }} /><b>{x.px}</b><span>{x.qty}</span><em>{(x.qty / 10).toFixed(0)}%</em></div>)}</div></div> }
function App() {
  const [active, setActive] = useState('Overview')
  const [selected, setSelected] = useState(markets[0])
  const [report, setReport] = useState(fallbackReport)
  const [updated, setUpdated] = useState(new Date())
  const [live, setLive] = useState(false)
  useEffect(() => { fetch('/api/report').then((r) => r.json()).then(setReport).catch(() => {}) }, [])
  const featureState = useMemo(() => ({ spread: selected.spread, imbalance: selected.yes - selected.no, microprice: selected.yes + (selected.spread / 2) }), [selected])
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">μ</div><div><strong>MICROSTRUCTURE</strong><small>RESEARCH CONSOLE</small></div></div>
      <div className="environment"><span className="pulse" /> REPLAY ENVIRONMENT <b>v0.4.0</b></div>
      <nav>{['Overview', 'Order Book', 'Execution Lab', 'Kalshi Markets', 'Research Reports'].map((item) => <button className={active === item ? 'nav-item active' : 'nav-item'} onClick={() => setActive(item)} key={item}>{item === 'Overview' && <Activity size={16} />}{item === 'Order Book' && <BookOpen size={16} />}{item === 'Execution Lab' && <SlidersHorizontal size={16} />}{item === 'Kalshi Markets' && <Layers3 size={16} />}{item === 'Research Reports' && <BarChart3 size={16} />}{item}<span>{item === 'Overview' ? '01' : item === 'Order Book' ? '02' : item === 'Execution Lab' ? '03' : item === 'Kalshi Markets' ? '04' : '05'}</span></button>)}</nav>
      <div className="side-spacer" /><div className="system-card"><div className="eyebrow"><ShieldCheck size={14} /> SAFETY CONTROLS</div><div className="safe-row"><span>Live trading</span><b className="off">DISABLED</b></div><div className="safe-row"><span>Credentials</span><b className="ok">NONE</b></div><div className="safe-row"><span>Data source</span><b>FIXTURE</b></div></div>
      <div className="profile"><div className="avatar">RP</div><div><strong>Raj's Lab</strong><small>read-only operator</small></div><ChevronDown size={15} /></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><div className="crumb">RESEARCH / {active.toUpperCase()}</div><h1>{active === 'Overview' ? 'Market microstructure, made measurable.' : active}</h1></div><div className="top-actions"><button className="icon-button" title="Help"><CircleHelp size={17} /></button><button className="icon-button" title="Refresh" onClick={() => { setUpdated(new Date()); setLive((x) => !x) }}><RefreshCw size={17} /></button><div className="connection"><Wifi size={15} /><span>{live ? 'API connected' : 'local fixtures'}</span><i className={live ? 'green' : ''} /></div></div></header>
      <div className="notice"><Radio size={16} /><span><b>Read-only research environment.</b> No orders are sent to any venue. Results combine deterministic replay and public Kalshi metadata.</span><time>UPDATED {updated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>
      <section className="metrics-grid"><Metric label="REPLAY THROUGHPUT" value="15.12M" detail="orders / second · M4 Air" tone="green-text" /><Metric label="SIMULATED INVENTORY" value="+184" detail="contracts · marked 0.55" tone="blue-text" /><Metric label="EXECUTION QUALITY" value="97.4%" detail="queue model confidence" tone="green-text" /><Metric label="RESEARCH STATUS" value="VALID" detail="5/5 C++ checks passing" tone="purple-text" /></section>
      <div className="content-grid"><section className="panel chart-panel"><SectionHeader icon={Activity} eyebrow="PORTFOLIO SIMULATION" title="Execution quality" action={<div className="segmented"><button className="selected">1H</button><button>1D</button><button>1W</button></div>} /><div className="chart-meta"><div><span>Net simulated PnL</span><strong>+$1,284.60</strong><b className="positive"><ArrowUpRight size={14} /> 8.42%</b></div><div className="chart-legend"><span><i className="dot green-dot" /> realized</span><span><i className="dot blue-dot" /> marked</span></div></div><div className="line-chart"><div className="grid-lines"><i /><i /><i /><i /></div><Sparkline points={[20, 25, 22, 29, 26, 38, 35, 43, 40, 48, 45, 57, 53, 62, 58, 70, 67, 78, 74, 82]} /><div className="chart-axis"><span>09:30</span><span>11:00</span><span>12:30</span><span>14:00</span><span>15:30</span></div></div></section><section className="panel book-panel"><SectionHeader icon={BookOpen} eyebrow="LIVE REPLAY SNAPSHOT" title={selected.ticker} action={<button className="select-market">{selected.venue}<ChevronDown size={14} /></button>} /><div className="book-title"><div><strong>{selected.title}</strong><small>YES contract · probability view</small></div><span className="status-badge"><i /> OPEN</span></div><OrderBook /><div className="book-footer"><span>queue ahead <b>1,240</b></span><span>last trade <b>0.55</b></span><span>depth <b>2.8K</b></span></div></section></div>
      <section className="panel markets-panel"><SectionHeader icon={Layers3} eyebrow="VENUE MONITOR" title="Kalshi opportunity surface" action={<button className="text-button" onClick={() => setActive('Kalshi Markets')}>View all <ArrowUpRight size={14} /></button>} /><div className="table-wrap"><table><thead><tr><th>MARKET</th><th>YES / NO</th><th>SPREAD</th><th>24H VOLUME</th><th>REWARD POOL</th><th>RESEARCH SIGNAL</th></tr></thead><tbody>{markets.map((m) => <tr key={m.ticker} onClick={() => setSelected(m)} className={selected.ticker === m.ticker ? 'row-selected' : ''}><td><div className="market-name"><span className="market-icon">K</span><div><strong>{m.title}</strong><small>{m.ticker}</small></div></div></td><td><span className="prob yes">{m.yes.toFixed(2)}</span><span className="slash">/</span><span className="prob no">{m.no.toFixed(2)}</span></td><td className="mono">{(m.spread * 100).toFixed(0)}¢</td><td className="mono">{m.volume}</td><td className="mono reward">{m.reward}</td><td><span className={m.spread < 0.03 ? 'signal good' : 'signal warn'}>{m.spread < 0.03 ? 'eligible' : 'thin book'}</span></td></tr>)}</tbody></table></div></section>
      <div className="bottom-grid"><section className="panel feature-panel"><SectionHeader icon={Gauge} eyebrow="MICROSTRUCTURE" title="Top-of-book features" action={<span className="tiny-label">{selected.ticker}</span>} /><div className="feature-grid"><Metric label="MICROPRICE" value={featureState.microprice.toFixed(3)} detail="weighted fair value" tone="blue-text" /><Metric label="IMBALANCE" value={`${featureState.imbalance >= 0 ? '+' : ''}${(featureState.imbalance * 100).toFixed(1)}%`} detail="bid − ask depth" tone={featureState.imbalance >= 0 ? 'green-text' : 'red-text'} /><Metric label="SPREAD" value={`${(featureState.spread * 100).toFixed(0)}¢`} detail="best ask − bid" /><Metric label="FILL PROBABILITY" value="64.8%" detail="queue-adjusted" tone="purple-text" /></div></section><section className="panel benchmark-panel"><SectionHeader icon={Terminal} eyebrow="ENGINE BENCHMARK" title="Hot-path performance" action={<span className="tiny-label">RELEASE · M4</span>} /><div className="bench-row"><span>Order submissions</span><b>15.12M/s</b><Sparkline points={[45, 48, 47, 50, 49, 51, 50, 53]} /></div><div className="bench-row"><span>p99 processing</span><b>78 ns</b><Sparkline points={[50, 48, 49, 47, 46, 47, 45, 44]} positive={false} /></div><div className="bench-row"><span>Replay determinism</span><b className="green-text">100%</b><span className="verified"><ShieldCheck size={14} /> verified</span></div></section></div>
      <footer><span>QUANT MARKET MICROSTRUCTURE LAB · C++20 / REACT / READ-ONLY</span><span><i className="pulse" /> SYSTEM HEALTHY</span></footer>
    </main>
  </div>
}
export default App
